steps:
  #build
- id: 'Build Container Image'
  name: 'gcr.io/cloud-builders/gcloud'
  dir: 'packages/api'
  args: ['builds','submit', '--tag', 'gcr.io/oss-automation/api']

  #deploy
- id: 'Deploy to Cloud Run'
  name: 'gcr.io/cloud-builders/gcloud'
  args: 
  - 'run'
  - 'deploy'
  - 'api'
  - '--image'
  - 'gcr.io/oss-automation/api'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
images:
  - 'gcr.io/oss-automation/api'