---
extends:
  - xo-react
rules:
  import/no-unassigned-import: warn
  import/extensions: warn
  react/state-in-constructor: off
  react/no-unused-state: warn
  react/jsx-pascal-case: warn
  react/jsx-indent: off
  react/jsx-indent-props: off
  react/require-default-props: off
  react/prop-types: warn
  camelcase: warn
  indent: ["error", 2]
