steps:
  #Install Dependencies
- name: 'node'
  entrypoint: 'npm'
  dir: 'packages/frontend'
  args: ['install']

  #Install Angular
- name: 'node'
  entrypoint: 'npm'
  dir: 'packages/frontend'
  args: ['install', '-g', '@angular/cli']

  #Install Firebase tools
- name: 'node'
  entrypoint: 'npm'
  dir: 'packages/frontend'
  args: ['install', '-g', 'firebase-tools']

  #Build
- name: 'node'
  entrypoint: 'npm'
  dir: 'packages/frontend'
  args: ['run', 'stage-build']

  #Deploy to Firebase
- name: 'gcr.io/${_PROJECT_ID}/firebase'
  dir: 'packages/frontend/deployment/staging'
  args: ['deploy', '--project=${_PROJECT_ID}', '--only=hosting']
